/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TripManagementImport } from './routes/trip-management'
import { Route as PhotoGalleryImport } from './routes/photo-gallery'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TripManagementRoute = TripManagementImport.update({
  id: '/trip-management',
  path: '/trip-management',
  getParentRoute: () => rootRoute,
} as any)

const PhotoGalleryRoute = PhotoGalleryImport.update({
  id: '/photo-gallery',
  path: '/photo-gallery',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/photo-gallery': {
      id: '/photo-gallery'
      path: '/photo-gallery'
      fullPath: '/photo-gallery'
      preLoaderRoute: typeof PhotoGalleryImport
      parentRoute: typeof rootRoute
    }
    '/trip-management': {
      id: '/trip-management'
      path: '/trip-management'
      fullPath: '/trip-management'
      preLoaderRoute: typeof TripManagementImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/photo-gallery': typeof PhotoGalleryRoute
  '/trip-management': typeof TripManagementRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/photo-gallery': typeof PhotoGalleryRoute
  '/trip-management': typeof TripManagementRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/photo-gallery': typeof PhotoGalleryRoute
  '/trip-management': typeof TripManagementRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/photo-gallery' | '/trip-management'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/photo-gallery' | '/trip-management'
  id: '__root__' | '/' | '/photo-gallery' | '/trip-management'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PhotoGalleryRoute: typeof PhotoGalleryRoute
  TripManagementRoute: typeof TripManagementRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PhotoGalleryRoute: PhotoGalleryRoute,
  TripManagementRoute: TripManagementRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/photo-gallery",
        "/trip-management"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/photo-gallery": {
      "filePath": "photo-gallery.tsx"
    },
    "/trip-management": {
      "filePath": "trip-management.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
